services:

  dataflux:
    image: dataflux:0.9.1
    container_name: dataflux

    ports:
      - "8028:8028"

    env_file:
      - .env

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ftp_data:/app/ftp_files
      - oss_data:/app/data/oss_files
      - ./large-v3:/app/large-v3
      - ./license.key:/app/license.key

    restart: unless-stopped

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  ftp_data:
  oss_data: