"""init

Revision ID: e3611e301954
Revises: 
Create Date: 2026-07-27 11:33:39.272931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3611e301954'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ftp_file_record',
    sa.Column('task_id', sa.String(length=32), nullable=False, comment='关联采集任务ID'),
    sa.Column('remote_path', sa.String(length=500), nullable=False, comment='FTP远程文件路径'),
    sa.Column('local_path', sa.String(length=500), nullable=True, comment='本地存储绝对路径'),
    sa.Column('file_name', sa.String(length=255), nullable=True, comment='文件名'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小(字节)'),
    sa.Column('md5', sa.String(length=32), nullable=True, comment='文件MD5，用于增量去重'),
    sa.Column('remote_mtime', sa.String(length=30), nullable=True, comment='远程文件修改时间，快速去重凭据'),
    sa.Column('remote_size', sa.BigInteger(), nullable=True, comment='远程文件大小，配合mtime做下载前去重'),
    sa.Column('file_type', sa.String(length=20), nullable=True, comment='文件类型: csv/json/yaml/binary'),
    sa.Column('is_parsed', sa.Integer(), nullable=False, comment='是否已解析入库(0未解析 1已解析)'),
    sa.Column('parsed_rows', sa.Integer(), nullable=False, comment='解析写入行数'),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True, comment='下载时间'),
    sa.Column('id', sa.String(length=32), nullable=False, comment='主键ID(UUID)'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('create_by', sa.String(length=50), nullable=True, comment='创建人姓名/ID'),
    sa.Column('is_delete', sa.Integer(), nullable=False, comment='是否删除(0正常 1删除)'),
    sa.PrimaryKeyConstraint('id'),
    comment='FTP 文件采集记录表'
    )
    op.create_index(op.f('ix_ftp_file_record_task_id'), 'ftp_file_record', ['task_id'], unique=False)
    op.create_table('oss_file_record',
    sa.Column('task_id', sa.String(length=32), nullable=False, comment='关联采集任务ID'),
    sa.Column('object_key', sa.String(length=500), nullable=False, comment='OSS对象Key(即文件完整路径)'),
    sa.Column('local_path', sa.String(length=500), nullable=True, comment='本地存储绝对路径'),
    sa.Column('file_name', sa.String(length=255), nullable=True, comment='文件名'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小(字节)'),
    sa.Column('md5', sa.String(length=32), nullable=True, comment='文件MD5，用于增量去重'),
    sa.Column('file_type', sa.String(length=20), nullable=True, comment='文件类型: csv/json/yaml/xlsx/xml/binary'),
    sa.Column('is_parsed', sa.Integer(), nullable=False, comment='是否已解析入库(0未解析 1已解析)'),
    sa.Column('parsed_rows', sa.Integer(), nullable=False, comment='解析写入行数'),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True, comment='首次下载时间'),
    sa.Column('id', sa.String(length=32), nullable=False, comment='主键ID(UUID)'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('create_by', sa.String(length=50), nullable=True, comment='创建人姓名/ID'),
    sa.Column('is_delete', sa.Integer(), nullable=False, comment='是否删除(0正常 1删除)'),
    sa.PrimaryKeyConstraint('id'),
    comment='OSS 对象存储文件采集记录表'
    )
    op.create_index(op.f('ix_oss_file_record_task_id'), 'oss_file_record', ['task_id'], unique=False)
    op.create_table('sync_execution_log',
    sa.Column('log_id', sa.String(length=32), nullable=False, comment='关联的TaskLog ID'),
    sa.Column('task_id', sa.String(length=32), nullable=False, comment='归属的任务ID'),
    sa.Column('source_table', sa.String(length=100), nullable=False, comment='源表名'),
    sa.Column('target_table', sa.String(length=100), nullable=False, comment='目标表名'),
    sa.Column('sync_mode', sa.String(length=20), nullable=False, comment='冲突策略: overwrite/skip/insert'),
    sa.Column('collect_mode', sa.String(length=20), nullable=False, comment='采集模式: full/inc_id/inc_time/custom_sql'),
    sa.Column('records_count', sa.Integer(), nullable=False, comment='本次同步条数'),
    sa.Column('cost_seconds', sa.Float(), nullable=False, comment='耗时(秒)'),
    sa.Column('watermark', sa.String(length=255), nullable=True, comment='本次高水位线'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='success/failed'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('id', sa.String(length=32), nullable=False, comment='主键ID(UUID)'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('create_by', sa.String(length=50), nullable=True, comment='创建人姓名/ID'),
    sa.Column('is_delete', sa.Integer(), nullable=False, comment='是否删除(0正常 1删除)'),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='表级同步执行日志(映射)'
    )
    op.create_index(op.f('ix_public_sync_execution_log_log_id'), 'sync_execution_log', ['log_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_sync_execution_log_target_table'), 'sync_execution_log', ['target_table'], unique=False, schema='public')
    op.create_index(op.f('ix_public_sync_execution_log_task_id'), 'sync_execution_log', ['task_id'], unique=False, schema='public')
    op.create_table('sys_collect_record',
    sa.Column('task_id', sa.String(length=32), nullable=False, comment='是由哪个采集任务采回来的'),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='来源类型(冗余字段方便查询)'),
    sa.Column('payload', sa.JSON(), nullable=False, comment='完整的异构数据载体'),
    sa.Column('id', sa.String(length=32), nullable=False, comment='主键ID(UUID)'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('create_by', sa.String(length=50), nullable=True, comment='创建人姓名/ID'),
    sa.Column('is_delete', sa.Integer(), nullable=False, comment='是否删除(0正常 1删除)'),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='异构原始数据落地表'
    )
    op.create_table('sys_collect_task',
    sa.Column('task_name', sa.String(length=100), nullable=False, comment='任务名称'),
    sa.Column('source_id', sa.String(length=32), nullable=False, comment='关联的数据源ID'),
    sa.Column('topic_or_table', sa.String(length=100), nullable=True, comment='custom_sql模式下目标库写入表名'),
    sa.Column('schedule_type', sa.String(length=20), nullable=False, comment='调度类型: none, cron, interval_min, daily, weekly'),
    sa.Column('schedule_value', sa.String(length=50), nullable=True, comment='调度值 (如 02:30)'),
    sa.Column('schedule_cron', sa.String(length=50), nullable=True, comment='定时任务表达式，为空则表示常驻流式任务'),
    sa.Column('status', sa.Integer(), nullable=False, comment='任务状态: 0停用, 1启用'),
    sa.Column('sync_mode', sa.String(length=20), nullable=False, comment='冲突策略: insert, overwrite, skip'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('sync_tables', sa.JSON(), nullable=True, comment='指定同步表'),
    sa.Column('table_mapping', sa.JSON(), nullable=True, comment="表名映射: {'源表名':'目标表名'}"),
    sa.Column('collect_mode', sa.String(length=20), nullable=False),
    sa.Column('incremental_column', sa.String(length=50), nullable=True),
    sa.Column('last_watermark', sa.String(length=255), nullable=True),
    sa.Column('custom_sql', sa.Text(), nullable=True),
    sa.Column('target_type', sa.String(length=20), nullable=False, comment='目标库类型: postgresql 或 mongodb'),
    sa.Column('target_host', sa.String(length=255), nullable=True, comment='目标库主机'),
    sa.Column('target_port', sa.Integer(), nullable=True, comment='目标库端口'),
    sa.Column('target_username', sa.String(length=100), nullable=True, comment='目标库账号'),
    sa.Column('target_password', sa.String(length=255), nullable=True, comment='目标库密码'),
    sa.Column('target_db_name', sa.String(length=100), nullable=True, comment='目标库名'),
    sa.Column('clean_policy', sa.String(length=20), nullable=True, comment='清理策略: none/by_days/by_count'),
    sa.Column('clean_keep_days', sa.Integer(), nullable=True, comment='按天保留: 保留最近N天数据'),
    sa.Column('clean_keep_count', sa.Integer(), nullable=True, comment='按条数保留: 保留最新N条'),
    sa.Column('clean_cron', sa.String(length=50), nullable=True, comment='自动清理的Cron表达式'),
    sa.Column('ftp_url', sa.String(length=500), nullable=True, comment='FTP完整URL,传了则自动解析覆盖连接参数'),
    sa.Column('ftp_path', sa.String(length=500), nullable=True, comment='FTP远程文件路径'),
    sa.Column('ftp_dir', sa.String(length=500), nullable=True, comment='批量模式: FTP远程根目录'),
    sa.Column('file_pattern', sa.String(length=100), nullable=False, comment='批量模式: 文件通配符'),
    sa.Column('is_recursive', sa.Integer(), nullable=False, comment='批量模式: 是否递归子目录 0/1'),
    sa.Column('ftp_passive', sa.Integer(), nullable=False, comment='是否被动模式(1是 0否)'),
    sa.Column('file_parse', sa.Integer(), nullable=False, comment='是否解析文件入库(1是 0否)'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='文件类型: auto/csv/json/yaml'),
    sa.Column('api_url', sa.String(length=500), nullable=True, comment='接口完整URL'),
    sa.Column('api_method', sa.String(length=10), nullable=False, comment='请求方法: GET/POST/PUT'),
    sa.Column('api_headers', sa.JSON(), nullable=True, comment='请求头'),
    sa.Column('api_body', sa.JSON(), nullable=True, comment='请求体或查询参数'),
    sa.Column('api_extract_mode', sa.String(length=10), nullable=False, comment='data/monitor/both'),
    sa.Column('api_data_path', sa.String(length=500), nullable=True, comment='响应体中业务数据的路径'),
    sa.Column('snmp_version', sa.String(length=10), nullable=False, comment='v1/v2c/v3'),
    sa.Column('snmp_community', sa.String(length=50), nullable=False, comment='v1/v2c团体字'),
    sa.Column('snmp_user', sa.String(length=100), nullable=True, comment='v3用户名'),
    sa.Column('snmp_auth_key', sa.String(length=255), nullable=True, comment='v3认证密码'),
    sa.Column('snmp_priv_key', sa.String(length=255), nullable=True, comment='v3加密密码'),
    sa.Column('snmp_auth_protocol', sa.String(length=10), nullable=False, comment='v3认证协议'),
    sa.Column('snmp_priv_protocol', sa.String(length=10), nullable=False, comment='v3加密协议'),
    sa.Column('snmp_extract_mode', sa.String(length=10), nullable=False, comment='metric/info/both'),
    sa.Column('snmp_metric_oids', sa.JSON(), nullable=True, comment='指标OID映射'),
    sa.Column('snmp_table_oids', sa.JSON(), nullable=True, comment='表格OID映射'),
    sa.Column('socket_protocol', sa.String(length=10), nullable=False, comment='tcp/udp'),
    sa.Column('socket_command', sa.Text(), nullable=True, comment='发送指令'),
    sa.Column('socket_command_encoding', sa.String(length=10), nullable=False, comment='编码'),
    sa.Column('socket_timeout', sa.Integer(), nullable=False, comment='超时秒数'),
    sa.Column('socket_recv_size', sa.Integer(), nullable=False, comment='缓冲区大小'),
    sa.Column('socket_terminator', sa.String(length=20), nullable=True, comment='结束符'),
    sa.Column('socket_response_format', sa.String(length=10), nullable=False, comment='响应格式'),
    sa.Column('kafka_bootstrap_servers', sa.String(length=255), nullable=True, comment='Kafka地址'),
    sa.Column('kafka_topic', sa.String(length=255), nullable=True, comment='订阅Topic'),
    sa.Column('kafka_group_id', sa.String(length=255), nullable=True, comment='消费组ID'),
    sa.Column('kafka_auto_offset_reset', sa.String(length=20), nullable=True),
    sa.Column('kafka_batch_size', sa.Integer(), nullable=True),
    sa.Column('kafka_batch_timeout_ms', sa.Integer(), nullable=True),
    sa.Column('kafka_value_format', sa.String(length=20), nullable=True),
    sa.Column('mqtt_broker', sa.String(length=255), nullable=True, comment='MQTT Broker地址'),
    sa.Column('mqtt_port', sa.Integer(), nullable=True),
    sa.Column('mqtt_topic', sa.String(length=255), nullable=True, comment='订阅Topic'),
    sa.Column('mqtt_client_id', sa.String(length=128), nullable=True, comment='客户端ID'),
    sa.Column('mqtt_qos', sa.Integer(), nullable=True),
    sa.Column('mqtt_clean_session', sa.Integer(), nullable=True, comment='0=持久会话'),
    sa.Column('mqtt_use_tls', sa.Integer(), nullable=True),
    sa.Column('mqtt_keepalive', sa.Integer(), nullable=True),
    sa.Column('mqtt_batch_size', sa.Integer(), nullable=True),
    sa.Column('mqtt_batch_timeout_ms', sa.Integer(), nullable=True),
    sa.Column('mqtt_value_format', sa.String(length=20), nullable=True),
    sa.Column('mq_host', sa.String(length=255), nullable=True),
    sa.Column('mq_port', sa.Integer(), nullable=True),
    sa.Column('mq_vhost', sa.String(length=128), nullable=True),
    sa.Column('mq_queue', sa.String(length=255), nullable=True),
    sa.Column('mq_exchange', sa.String(length=255), nullable=True),
    sa.Column('mq_exchange_type', sa.String(length=20), nullable=True),
    sa.Column('mq_routing_key', sa.String(length=255), nullable=True),
    sa.Column('mq_durable', sa.Integer(), nullable=True),
    sa.Column('mq_prefetch_count', sa.Integer(), nullable=True),
    sa.Column('mq_batch_size', sa.Integer(), nullable=True),
    sa.Column('mq_batch_timeout_ms', sa.Integer(), nullable=True),
    sa.Column('mq_value_format', sa.String(length=20), nullable=True),
    sa.Column('oss_endpoint', sa.String(length=255), nullable=True, comment='对象存储的 Endpoint 地址 (如: https://oss-cn-hangzhou.aliyuncs.com)'),
    sa.Column('oss_access_key', sa.String(length=128), nullable=True, comment='访问密钥 AccessKeyId'),
    sa.Column('oss_secret_key', sa.String(length=255), nullable=True, comment='私有密钥 AccessKeySecret'),
    sa.Column('oss_bucket', sa.String(length=128), nullable=True, comment='存储桶 Bucket 名称'),
    sa.Column('oss_region', sa.String(length=64), nullable=True, comment='存储区域 Region (如: cn-hangzhou),部分私有 S3 必须指定'),
    sa.Column('oss_object_key', sa.String(length=500), nullable=True, comment='单文件模式: 指定要拉取的完整对象路径 (如: data/2026/config.json)'),
    sa.Column('oss_prefix', sa.String(length=500), nullable=True, comment='批量前缀模式: 指定要拉取的目录前缀 (如: logs/2026-06/)'),
    sa.Column('oss_max_keys', sa.Integer(), nullable=True, comment='批量模式下单次 API 请求返回的最大对象数量 (用于分页处理)'),
    sa.Column('oss_use_ssl', sa.Integer(), nullable=True, comment='是否通过 HTTPS 加密传输协议连接 (1=是, 0=否)'),
    sa.Column('oss_addressing_style', sa.String(length=20), nullable=True, comment='寻址风格: virtual=虚拟主机风格(阿里云/AWS常用), path=路径风格(自建 MinIO 常用)'),
    sa.Column('id', sa.String(length=32), nullable=False, comment='主键ID(UUID)'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('create_by', sa.String(length=50), nullable=True, comment='创建人姓名/ID'),
    sa.Column('is_delete', sa.Integer(), nullable=False, comment='是否删除(0正常 1删除)'),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='数据采集任务定义表'
    )
    op.create_table('sys_data_source',
    sa.Column('name', sa.String(length=100), nullable=False, comment='数据源名称，如：产线A_MySQL'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='数据源类型：mysql, mqtt, kafka, redis'),
    sa.Column('host', sa.String(length=255), nullable=False, comment='主机地址(API/Kafka等可填空)'),
    sa.Column('port', sa.Integer(), nullable=False, comment='端口(API/Kafka等可填0)'),
    sa.Column('db_name', sa.String(length=100), nullable=True, comment='数据库名称'),
    sa.Column('username', sa.String(length=100), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='密码(建议密文存储)'),
    sa.Column('config_json', sa.JSON(), nullable=True, comment='其他特有配置(如SSL证书路径等)'),
    sa.Column('id', sa.String(length=32), nullable=False, comment='主键ID(UUID)'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('create_by', sa.String(length=50), nullable=True, comment='创建人姓名/ID'),
    sa.Column('is_delete', sa.Integer(), nullable=False, comment='是否删除(0正常 1删除)'),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='数据源配置表'
    )
    op.create_table('sys_oper_log',
    sa.Column('id', sa.String(length=32), nullable=False, comment='主键ID(UUID)'),
    sa.Column('title', sa.String(length=50), nullable=True, comment='模块标题'),
    sa.Column('business_type', sa.Integer(), nullable=True, comment='业务类型 (如: 1新增 2修改 3删除)'),
    sa.Column('oper_name', sa.String(length=50), nullable=True, comment='操作人员'),
    sa.Column('oper_ip', sa.String(length=50), nullable=True, comment='主机地址'),
    sa.Column('oper_param', sa.Text(), nullable=True, comment='请求参数'),
    sa.Column('json_result', sa.Text(), nullable=True, comment='返回参数'),
    sa.Column('status', sa.Integer(), nullable=True, comment='操作状态 (0正常 1异常)'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='错误消息'),
    sa.Column('oper_time', sa.DateTime(), nullable=True, comment='操作时间'),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='系统操作日志表'
    )
    op.create_table('sys_task_log',
    sa.Column('task_id', sa.String(length=32), nullable=False, comment='关联的任务ID'),
    sa.Column('task_name', sa.String(length=100), nullable=False, comment='任务名称快照'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='执行状态'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('tables_synced', sa.Integer(), nullable=False, comment='同步表数量'),
    sa.Column('total_records', sa.Integer(), nullable=False, comment='同步总条数'),
    sa.Column('detail_json', sa.JSON(), nullable=True, comment='执行详情快照(策略/表名/条数/水位线)'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='失败原因'),
    sa.Column('id', sa.String(length=32), nullable=False, comment='主键ID(UUID)'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('create_by', sa.String(length=50), nullable=True, comment='创建人姓名/ID'),
    sa.Column('is_delete', sa.Integer(), nullable=False, comment='是否删除(0正常 1删除)'),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='任务执行历史日志表'
    )
    op.create_index(op.f('ix_public_sys_task_log_task_id'), 'sys_task_log', ['task_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_sys_task_log_task_id'), table_name='sys_task_log', schema='public')
    op.drop_table('sys_task_log', schema='public')
    op.drop_table('sys_oper_log', schema='public')
    op.drop_table('sys_data_source', schema='public')
    op.drop_table('sys_collect_task', schema='public')
    op.drop_table('sys_collect_record', schema='public')
    op.drop_index(op.f('ix_public_sync_execution_log_task_id'), table_name='sync_execution_log', schema='public')
    op.drop_index(op.f('ix_public_sync_execution_log_target_table'), table_name='sync_execution_log', schema='public')
    op.drop_index(op.f('ix_public_sync_execution_log_log_id'), table_name='sync_execution_log', schema='public')
    op.drop_table('sync_execution_log', schema='public')
    op.drop_index(op.f('ix_oss_file_record_task_id'), table_name='oss_file_record')
    op.drop_table('oss_file_record')
    op.drop_index(op.f('ix_ftp_file_record_task_id'), table_name='ftp_file_record')
    op.drop_table('ftp_file_record')
    # ### end Alembic commands ###
